-- MySQL Script generated by MySQL Workbench
-- Fri Aug  4 14:30:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`bait`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bait` (
  `idbait` INT NOT NULL AUTO_INCREMENT,
  `bait` VARCHAR(45) NOT NULL,
  `target` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbait`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`regions` (
  `idregions` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idregions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(45) NOT NULL,
  `park` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trap` (
  `idtrap` INT NOT NULL AUTO_INCREMENT,
  `marker_number` INT NULL,
  `trap_loc` INT NULL,
  `trap_notes` VARCHAR(45) NULL,
  `bait_idbait` INT NOT NULL,
  `regions_idregions` INT NOT NULL,
  `parks_idparks` INT NOT NULL,
  PRIMARY KEY (`idtrap`),
  INDEX `fk_trap_bait_idx` (`bait_idbait` ASC) VISIBLE,
  INDEX `fk_trap_regions1_idx` (`regions_idregions` ASC) VISIBLE,
  INDEX `fk_trap_parks1_idx` (`parks_idparks` ASC) VISIBLE,
  CONSTRAINT `fk_trap_bait`
    FOREIGN KEY (`bait_idbait`)
    REFERENCES `mydb`.`bait` (`idbait`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trap_regions1`
    FOREIGN KEY (`regions_idregions`)
    REFERENCES `mydb`.`regions` (`idregions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trap_parks1`
    FOREIGN KEY (`parks_idparks`)
    REFERENCES `mydb`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `create_time` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
